use proc_macro::TokenStream;
use quote::quote;
use syn::{parse_macro_input, ItemFn};

#[proc_macro_derive(Describe)]
pub fn derive_describe(input: TokenStream) -> TokenStream {
    let input = parse_macro_input!(input as syn::DeriveInput);
    let name = input.ident;
    let type_name = name.to_string();

    let expanded = quote! {
        impl #name {
            pub fn describe(&self) -> String {
                format!("{} generated by #[derive(Describe)]", #type_name)
            }
        }
    };

    expanded.into()
}

#[proc_macro]
pub fn make_answer(_input: TokenStream) -> TokenStream {
    quote! {
        42
    }
    .into()
}

#[proc_macro_attribute]
pub fn log_call(_attr: TokenStream, item: TokenStream) -> TokenStream {
    let function = parse_macro_input!(item as ItemFn);
    let visibility = &function.vis;
    let signature = &function.sig;
    let block = &function.block;
    let name = signature.ident.to_string();

    let expanded = quote! {
        #visibility #signature {
            println!("entering function `{}`", #name);
            let __macro_result = (|| #block)();
            println!("leaving function `{}`", #name);
            __macro_result
        }
    };

    expanded.into()
}
